# PDF Outline Extractor v2.0 - Configuration
# Advanced AI-powered configuration for different use cases

# Detection Strategy Weights (must sum to 1.0)
strategy_weights:
  rule_based: 0.35        # Rule-based heuristic analysis
  ml_classification: 0.25 # Machine learning classification  
  semantic_analysis: 0.20 # NLP semantic analysis
  layout_analysis: 0.15   # Advanced layout analysis
  consensus: 0.05         # Cross-method consensus bonus

# Font Analysis Configuration
font_analysis:
  # Font size ratio thresholds relative to document average
  h1_min_ratio: 1.4      # Minimum ratio for H1 headings
  h2_min_ratio: 1.2      # Minimum ratio for H2 headings  
  h3_min_ratio: 1.1      # Minimum ratio for H3 headings
  
  # Z-score thresholds for statistical font analysis
  h1_min_zscore: 2.0     # H1 minimum Z-score
  h2_min_zscore: 1.5     # H2 minimum Z-score
  h3_min_zscore: 1.0     # H3 minimum Z-score

# Position-based Detection Rules
position_rules:
  left_margin_tolerance: 20      # Pixels from left margin
  center_tolerance_ratio: 0.15   # Ratio of page width for centering
  whitespace_threshold: 15       # Minimum vertical whitespace before heading
  top_page_ratio: 0.3           # Top 30% of page more likely for headings

# Text Pattern Configuration
pattern_matching:
  # Enable/disable different pattern types
  numbered_sections: true        # 1., 1.1., 1.1.1. patterns
  chapter_markers: true         # Chapter, Section, Part markers
  roman_numerals: true          # I., II., III. patterns
  letter_numbering: true        # A., B., C. patterns
  content_markers: true         # Introduction, Conclusion, etc.
  
  # Pattern confidence scores
  numbered_section_confidence: 0.9
  chapter_marker_confidence: 0.95
  content_marker_confidence: 0.8

# Semantic Analysis Configuration  
semantic_analysis:
  # Language detection settings
  enable_language_detection: true
  supported_languages:
    - english
    - japanese
    - chinese
    - french
    - german
    - spanish
  
  # Vocabulary analysis
  enable_vocabulary_analysis: true
  vocabulary_domains:
    - academic
    - technical
    - business
    - legal
  
  # Text classification confidence thresholds
  heading_probability_threshold: 0.3
  semantic_confidence_threshold: 0.5

# Machine Learning Configuration
ml_classification:
  # Model parameters
  model_type: "random_forest"    # random_forest, gradient_boosting, logistic_regression
  enable_feature_selection: true
  max_features: 50              # Maximum number of features to use
  
  # Training parameters
  cross_validation_folds: 5
  test_size: 0.2
  random_state: 42
  
  # Model hyperparameters
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
  
  gradient_boosting:
    n_estimators: 50
    learning_rate: 0.1
    max_depth: 6
  
  logistic_regression:
    max_iter: 1000
    C: 1.0

# Performance Optimization
performance:
  # Processing limits
  max_pages: 50                 # Maximum pages to process
  max_blocks_per_page: 1000     # Memory management
  enable_parallel_processing: true
  max_workers: 4                # Parallel processing workers
  
  # Memory management
  enable_garbage_collection: true
  gc_frequency: 10              # GC every N pages
  max_memory_mb: 1000          # Maximum memory usage
  
  # Caching
  enable_font_caching: true
  enable_pattern_caching: true
  cache_size_limit: 1000       # Maximum cached items

# Output Configuration
output:
  # JSON formatting
  indent: 2
  ensure_ascii: false
  sort_keys: false
  
  # Output validation
  validate_hierarchy: true      # Ensure H1->H2->H3 progression
  remove_duplicates: true       # Remove duplicate headings
  min_confidence_threshold: 0.4 # Minimum confidence for output
  
  # Metadata inclusion
  include_metadata: true
  include_debug_info: false     # Include debug information
  include_confidence_scores: false

# Quality Assurance
quality_assurance:
  # Minimum requirements
  min_word_count: 1            # Minimum words for heading
  max_word_count: 25           # Maximum words for heading
  min_char_count: 2            # Minimum characters
  max_char_count: 200          # Maximum characters
  
  # Content filtering
  filter_page_numbers: true    # Remove page numbers
  filter_headers_footers: true # Remove headers/footers
  filter_urls: true           # Remove URLs
  filter_copyright: true      # Remove copyright notices
  
  # Hierarchy validation
  enforce_hierarchy: true     # Ensure logical level progression
  max_same_level_consecutive: 10  # Max consecutive same-level headings

# Debugging and Logging
debugging:
  log_level: "INFO"           # DEBUG, INFO, WARNING, ERROR
  enable_performance_logging: true
  enable_method_contribution_tracking: true
  log_feature_importance: false
  save_intermediate_results: false

# Multilingual Support (Bonus Feature)
multilingual:
  enable_multilingual: true
  
  # Language-specific patterns
  japanese:
    chapter_markers: ["第", "章", "節", "項"]
    numbering: ["一", "二", "三", "四", "五"]
  
  chinese:
    chapter_markers: ["第", "章", "节", "条"] 
    numbering: ["一", "二", "三", "四", "五"]
  
  french:
    chapter_markers: ["chapitre", "section", "partie"]
  
  german:
    chapter_markers: ["kapitel", "abschnitt", "teil"]
    
  spanish:
    chapter_markers: ["capítulo", "sección", "parte"]

# Experimental Features
experimental:
  enable_advanced_layout_analysis: true
  enable_table_detection: true
  enable_image_area_detection: true
  enable_cross_reference_analysis: false
  enable_citation_detection: false

# Docker and Deployment
deployment:
  # Resource limits
  memory_limit: "2g"
  cpu_limit: "4"
  processing_timeout: 300      # 5 minutes max processing time
  
  # Health check
  health_check_interval: 30
  health_check_timeout: 10
  
  # Monitoring
  enable_metrics_collection: true
  metrics_retention_days: 7